services:
  frankenphp:
    image: dunglas/frankenphp:latest
    container_name: ember-frankenphp-local
    ports:
      - "8080:8080"
      - "2019:2019"
    volumes:
      - ./public:/app/public
      - ./Caddyfile:/etc/frankenphp/Caddyfile
